image:
  tag: v0.1.3
  pullPolicy: IfNotPresent
  repository: gcr.io/google-samples/microservices-demo/frontend


replicaCount: 1

service:
#  type: ClusterIP
  type: NodePort
  NodePort: 30001
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: shop.158.160.131.174.sslip.io