- name: Start deploy 
  hosts: test-kub
  remote_user: devops
  become: yes
  become_method: sudo
  #vars_files: 
  #         - ../defaults/main.yml
  tasks:
    - name: Creates directory
      file:
        path: kubernetes-operators
        state: directory
    
    - name: Creates directory
      file:
        path: kubernetes-operators/deploy
        state: directory

    - name: copy1  
      template:
        src: deploy/cr.yml
        dest: kubernetes-operators/deploy/cr.yml

    - name: copy2  
      template:
        src: deploy/crd.yml
        dest: kubernetes-operators/deploy/crd.yml