- name: Start copy docker
  hosts: test-kub
  remote_user: devops
  become: yes
  become_method: sudo
  #vars_files: 
  #         - ../defaults/main.yml
  tasks:
    - name: Creates directory
      file:
        path: web
        state: directory
    
    - name: copy1  
      template:
        src: kubernetes-intro/web/Dockerfile
        dest: web/Dockerfile
    
    - name: copy2
      template:
        src: kubernetes-intro/web/index.html
        dest: web/index.html

    - name: copy3  
      template:
        src: kubernetes-intro/web/homework.html
        dest: web/homework.html
    
    - name: copy4
      template:
        src: kubernetes-intro/web/nginx.conf
        dest: web/nginx.conf

    - name: copy5
      template:
        src: kubernetes-intro/web-pod.yaml
        dest: web/web-pod.yaml

       
      
      
    
        
