- name: Start deploy 
  hosts: test-kub
  remote_user: devops
  become: yes
  become_method: sudo
  #vars_files: 
  #         - ../defaults/main.yml
  tasks:
    - name: Creates directory
      file:
        path: kubernetes-networks
        state: directory
    
    - name: copy1  
      template:
        src: web-pod.yaml
        dest: kubernetes-networks/web-pod.yaml
       
    
    