apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web-nginx
      image: zagretdinov/web:latest
      livenessProbe:
        tcpSocket:  
          port: 8000 
      readinessProbe:
        httpGet:
          path: /index.html
          port: 8000
      imagePullPolicy: Always
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: init-web
      image: busybox:latest
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  restartPolicy: Always
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  volumes:
    - name: app
      emptyDir: {}