---
- name: Update repositories and install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ node_required_packages }}"

- name: Add Google Cloud public signing key
  apt_key:
    url: "{{ node_signing_key }}"
    state: present

- name: Add the Kubernetes apt repository
  apt_repository:
    repo: "{{ node_repo }}"
    state: present

- name: Install Kubernetes binaries
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    force: true
  loop: "{{ node_packages }}"