---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-reading
  namespace: prometheus
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]