apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9113'
  labels:
    app: nginx-exporter
spec:
  selector:
    app: nginx-exporter
  type: ClusterIP
  ports:
    - name: port-mon
      protocol: TCP
      port: 80
      targetPort: 9113