apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  endpoints:
  - port: port-mon