apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 0%
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: zagretdinov/web:latest
        livenessProbe:
          tcpSocket:
            port: 8080
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080