- name: Start deploy 
  hosts: test-kub
  remote_user: devops
  become: yes
  become_method: sudo
  #vars_files: 
  #         - ../defaults/main.yml
  tasks:
    - name: Creates directory
      file:
        path: kubernetes-security
        state: directory
    
    - name: Creates directory
      file:
        path: kubernetes-security/task01
        state: directory
    
    - name: copy1  
      template:
        src: task01/bob-serviceaccount.yaml
        dest: kubernetes-security/task01/bob-serviceaccount.yaml
   
    - name: copy2
      template:
        src: task01/bob-rolebinding.yaml
        dest: kubernetes-security/task01/bob-rolebinding.yaml
   

    - name: copy3
      template:
        src: task01/dave-serviceaccount.yaml
        dest: kubernetes-security/task01/dave-serviceaccount.yaml


    - name: Creates directory
      file:
        path: kubernetes-security/task02
        state: directory
    
    - name: copy4  
      template:
        src: task02/namespace-prometheus.yaml
        dest: kubernetes-security/task02/namespace-prometheus.yaml
   
    - name: copy5
      template:
        src: task02/serviceaccount-carol.yaml
        dest: kubernetes-security/task02/serviceaccount-carol.yaml
   

    - name: copy6
      template:
        src: task02/prometheus-role.yaml
        dest: kubernetes-security/task02/prometheus-role.yaml

    - name: copy7
      template:
        src: task02/rolebinding-pods.yaml
        dest: kubernetes-security/task02/rolebinding-pods.yaml