repositories:

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: jetstack
    url: https://charts.jetstack.io

  - name: chartmuseum
    url: https://chartmuseum.github.io/charts

  - name: harbor
    url: https://helm.goharbor.io

releases:
  - name: nginx-ingress-release
    createNamespace: true
    namespace: nginx-ingress
    chart: ingress-nginx/ingress-nginx
    version: 4.4.2

  - name: cert-manager
    createNamespace: true
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.11.0
    wait: true
    set:
      - name: installCRDs
        value: true

  - name: chartmuseum
    createNamespace: true
    namespace: chartmuseum
    chart: chartmuseum/chartmuseum
    version: 3.1.0
    values:
      - ./values/chartmuseum/values.yaml

  - name: harbor
    createNamespace: true
    namespace: harbor
    chart: harbor/harbor
    version: 1.11.0
    values:
      - ./values/harbor/values.yaml