- name: Start copy docker
  hosts: test-kub
  remote_user: devops
  become: yes
  become_method: sudo
  #vars_files: 
  #         - ../defaults/main.yml
  tasks:
    - name: Creates directory
      file:
        path: controllers
        state: directory
    
    - name: copy1  
      template:
        src: kind-config.yaml
        dest: controllers/kind-config.yaml
   
   