apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
namespace: hipster-shop-prod
namePrefix: prod-
patchesStrategicMerge:
  - replicas.yaml
  - memory.yaml
images:
  - name: adservice
    newName: gcr.io/google-samples/microservices-demo/adservice
    newTag: v0.5.1